# Generated by Django 4.1.1 on 2023-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoriabebidas_bebidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='saludable',
            field=models.BooleanField(default=False),
        ),
    ]
