# Generated by Django 3.2.19 on 2023-06-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_precio_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Excelente', max_length=20),
        ),
    ]
