# Generated by Django 4.1.1 on 2022-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentarios_delete_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-fecha_modificacion']},
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='publicado',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
