# Generated by Django 4.1.1 on 2022-10-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comentarios_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='texto',
            new_name='contenido',
        ),
    ]
