# Generated by Django 4.1.1 on 2022-11-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_texto_comentarios_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
